import { env } from "../config/env.js";
import { companiesRepository } from "../repositories/companies.js";
import { productsRepository } from "../repositories/products.js";
import { tasksRepository } from "../repositories/tasks.js";
import { generateKeywords } from "../utils/keywords.js";
import { normalizeUrl, rootDomain, isExcludedDomain } from "../utils/url.js";
import { scoreLead } from "../services/scoring.js";
import { SerpApiProvider } from "../services/search/serpapi.js";
const delay=(ms:number)=>new Promise(resolve=>setTimeout(resolve,ms));
export class SearchWorker {
  private running=false; private timer?:NodeJS.Timeout; private provider=new SerpApiProvider();
  start(){this.timer=setInterval(()=>void this.tick(),env.WORKER_POLL_MS);void this.tick();}
  stop(){if(this.timer)clearInterval(this.timer)}
  async tick(){if(this.running)return;this.running=true;let activeTaskId:string|undefined;try{const task=await tasksRepository.nextQueued();if(!task)return;activeTaskId=task.id;await tasksRepository.update(task.id,{status:"running",startedAt:new Date().toISOString(),progress:1});const product=await productsRepository.get(task.productId);const keywords=generateKeywords(product,task.country,task.maxKeywords);await tasksRepository.update(task.id,{keywords,keywordCount:keywords.length,progress:5});const discovered=new Map<string,{website:string;title:string;snippet:string}>();for(let i=0;i<keywords.length;i++){const results=await this.provider.search({keyword:keywords[i],country:task.country,language:task.language,maxResults:task.maxResults});for(const result of results){const website=normalizeUrl(result.url);const domain=website&&rootDomain(website);if(domain&&!isExcludedDomain(domain)&&!discovered.has(domain))discovered.set(domain,{website,title:result.title,snippet:result.snippet});}await tasksRepository.update(task.id,{domainsFound:discovered.size,progress:5+Math.round((i+1)/Math.max(keywords.length,1)*45)});await delay(env.SEARCH_REQUEST_DELAY_MS)}const entries=[...discovered.entries()].slice(0,env.MAX_COMPANIES_PER_TASK);let valid=0;for(let i=0;i<entries.length;i++){const [domain,hit]=entries[i];const assessment=scoreLead(`${hit.title} ${hit.snippet}`);if(assessment.score>=task.minScore)valid++;await companiesRepository.upsert({name:hit.title||domain,domain,website:hit.website,country:task.country,applications:product.applications,relevantProducts:[product.englishName],leadScore:assessment.score,leadGrade:assessment.grade,scoreDetails:assessment.details,evidenceSummary:hit.snippet,evidenceUrl:hit.website,developmentStatus:"未联系",priority:false,sourceTaskId:task.id});await tasksRepository.update(task.id,{companiesProcessed:i+1,validCompanies:valid,progress:50+Math.round((i+1)/Math.max(entries.length,1)*48)});}await tasksRepository.update(task.id,{status:"completed",progress:100,completedAt:new Date().toISOString()});}catch(error){const message=error instanceof Error?error.message:"未知任务错误";console.error("Search worker failed:",message);try{if(activeTaskId)await tasksRepository.update(activeTaskId,{status:"failed",errorMessage:message,completedAt:new Date().toISOString()});}catch{ /* avoid leaking config details */ }}finally{this.running=false}}
}
