services:
  lead-finder-api:
    build: .
    env_file: .env
    container_name: lead-finder-api
    restart: unless-stopped
    environment:
      HOST: 0.0.0.0
      PORT: 3000
      VIRTUAL_HOST: ${VIRTUAL_HOST}
      VIRTUAL_PORT: 3000
      LETSENCRYPT_HOST: ${LETSENCRYPT_HOST}
      LETSENCRYPT_EMAIL: ${LETSENCRYPT_EMAIL}
    expose:
      - "3000"
    networks:
      - web

networks:
  web:
    external: true
