import { env } from "../config/env.js";
import type { Company } from "../types/domain.js";
import { checkbox,date,email,multi,number,plain,relation,requireDatabase,requireNotion,select,text,title,url } from "./notion.js";
const db=()=>requireDatabase(env.NOTION_COMPANIES_DATABASE_ID,"Companies");
function map(page:any):Company{const p=page.properties;return{id:page.id,name:plain(p.Name),localName:plain(p["Local Name"])||undefined,domain:url(p.Domain),website:url(p.Website),country:select(p.Country)||undefined,region:plain(p.Region)||undefined,city:plain(p.City)||undefined,address:plain(p.Address)||undefined,postalCode:plain(p["Postal Code"])||undefined,phone:p.Phone?.phone_number||undefined,generalEmail:email(p["General Email"])||undefined,companyType:select(p["Company Type"])||undefined,applications:multi(p.Applications),relevantProducts:multi(p["Relevant Products"]),description:plain(p.Description)||undefined,leadScore:number(p["Lead Score"]),leadGrade:(select(p["Lead Grade"])||"D") as Company["leadGrade"],scoreDetails:plain(p["Score Details"]),evidenceSummary:plain(p["Evidence Summary"])||undefined,evidenceUrl:url(p["Evidence URL"])||undefined,developmentStatus:select(p["Development Status"])||"未联系",priority:checkbox(p.Priority),sourceTaskId:relation(p["Source Task"])||undefined,firstFoundAt:date(p["First Found At"])||page.created_time,lastVerifiedAt:date(p["Last Verified At"])||page.last_edited_time,updatedAt:date(p["Updated At"])||page.last_edited_time}}
export const companiesRepository={
 async list(filters:{country?:string;leadGrade?:string}={}):Promise<Company[]>{const and:any[]=[];if(filters.country)and.push({property:"Country",select:{equals:filters.country}});if(filters.leadGrade)and.push({property:"Lead Grade",select:{equals:filters.leadGrade}});const r:any=await requireNotion().databases.query({database_id:db(),page_size:100,filter:and.length?{and}:undefined,sorts:[{property:"Lead Score",direction:"descending"}]});return r.results.map(map)},
 async findByDomain(domain:string):Promise<Company|undefined>{const r:any=await requireNotion().databases.query({database_id:db(),filter:{property:"Domain",url:{equals:`https://${domain}`}},page_size:1});return r.results[0]?map(r.results[0]):undefined},
 async upsert(input:Omit<Company,"id"|"updatedAt"|"firstFoundAt"|"lastVerifiedAt">):Promise<Company>{const found=await this.findByDomain(input.domain);const now=new Date().toISOString();const p:any={Name:{title:title(input.name)},Domain:{url:`https://${input.domain}`},Website:{url:input.website},Country:input.country?{select:{name:input.country}}:{select:null},Applications:{multi_select:input.applications.map(name=>({name}))},"Relevant Products":{multi_select:input.relevantProducts.map(name=>({name}))},"Lead Score":{number:input.leadScore},"Lead Grade":{select:{name:input.leadGrade}},"Score Details":{rich_text:text(input.scoreDetails)},"Evidence Summary":{rich_text:text(input.evidenceSummary)},"Evidence URL":{url:input.evidenceUrl||null},"Development Status":{select:{name:input.developmentStatus}},Priority:{checkbox:input.priority},"Source Task":input.sourceTaskId?{relation:[{id:input.sourceTaskId}]}:{relation:[]},"Last Verified At":{date:{start:now}},"Updated At":{date:{start:now}}};if(found)return map(await requireNotion().pages.update({page_id:found.id,properties:p}) as any);const r:any=await requireNotion().pages.create({parent:{database_id:db()},properties:{...p,"First Found At":{date:{start:now}}}});return map(r)}
};

