import { env } from "../config/env.js";
import type { Product } from "../types/domain.js";
import { date, multi, plain, requireDatabase, requireNotion, select, text, title } from "./notion.js";

const db = () => requireDatabase(env.NOTION_PRODUCTS_DATABASE_ID, "Products");
function map(page: any): Product { const p = page.properties; return { id: page.id, name: plain(p.Name), englishName: plain(p["English Name"]), description: plain(p.Description), properties: plain(p.Properties), applications: multi(p.Applications), companyTypes: multi(p["Company Types"]), countries: multi(p.Countries), languages: multi(p.Languages), customKeywords: plain(p["Custom Keywords"]).split("\n").filter(Boolean), excludeKeywords: plain(p["Exclude Keywords"]).split("\n").filter(Boolean), status: (select(p.Status) || "active") as Product["status"], createdAt: date(p["Created At"]) || page.created_time, updatedAt: date(p["Updated At"]) || page.last_edited_time }; }
export const productsRepository = {
  async list(): Promise<Product[]> { const r: any = await requireNotion().databases.query({ database_id: db(), page_size: 100 }); return r.results.map(map); },
  async get(id: string): Promise<Product> { return map(await requireNotion().pages.retrieve({ page_id: id })); },
  async create(input: Omit<Product, "id" | "createdAt" | "updatedAt" | "status"> & { status?: Product["status"] }): Promise<Product> { const now = new Date().toISOString(); const r: any = await requireNotion().pages.create({ parent: { database_id: db() }, properties: { Name:{title:title(input.name)}, "English Name":{rich_text:text(input.englishName)}, Description:{rich_text:text(input.description)}, Properties:{rich_text:text(input.properties)}, Applications:{multi_select:input.applications.map(name=>({name}))}, "Company Types":{multi_select:input.companyTypes.map(name=>({name}))}, Countries:{multi_select:(input.countries||[]).map(name=>({name}))}, Languages:{multi_select:(input.languages||[]).map(name=>({name}))}, "Custom Keywords":{rich_text:text(input.customKeywords.join("\n"))}, "Exclude Keywords":{rich_text:text(input.excludeKeywords.join("\n"))}, Status:{select:{name:input.status||"active"}}, "Created At":{date:{start:now}}, "Updated At":{date:{start:now}} } }); return map(r); },
  async update(id: string, input: Partial<Product>): Promise<Product> { const props: any = { "Updated At": {date:{start:new Date().toISOString()}} }; if(input.name)props.Name={title:title(input.name)}; if(input.englishName)props["English Name"]={rich_text:text(input.englishName)}; if(input.description)props.Description={rich_text:text(input.description)}; if(input.applications)props.Applications={multi_select:input.applications.map(name=>({name}))}; if(input.companyTypes)props["Company Types"]={multi_select:input.companyTypes.map(name=>({name}))}; if(input.customKeywords)props["Custom Keywords"]={rich_text:text(input.customKeywords.join("\n"))}; if(input.excludeKeywords)props["Exclude Keywords"]={rich_text:text(input.excludeKeywords.join("\n"))}; if(input.status)props.Status={select:{name:input.status}}; return map(await requireNotion().pages.update({page_id:id,properties:props}) as any); }
};

