import "dotenv/config";
import { Client } from "@notionhq/client";
const token=process.env.NOTION_TOKEN;const parentId=process.env.NOTION_PARENT_PAGE_ID;if(!token||!parentId)throw new Error("请先在 .env 中填写 NOTION_TOKEN 与 NOTION_PARENT_PAGE_ID。");
const notion=new Client({auth:token});const parent={type:"page_id" as const,page_id:parentId};
const title={title:{}};const rich={rich_text:{}};const multi={multi_select:{}};const select=(names:string[])=>({select:{options:names.map(name=>({name}))}});const date={date:{}};const relation=(database_id:string)=>({relation:{database_id}});const url={url:{}};const number={number:{}};const email={email:{}};const phone={phone_number:{}};const checkbox={checkbox:{}};
async function create(titleText:string,properties:any){const result:any=await notion.databases.create({parent,title:[{type:"text",text:{content:titleText}}],properties});return result.id}
const products=await create("Lead Finder · Products",{Name:title,"English Name":rich,Description:rich,Properties:rich,Applications:multi,"Company Types":multi,Countries:multi,Languages:multi,"Custom Keywords":rich,"Exclude Keywords":rich,Status:select(["active","archived"]),"Created At":date,"Updated At":date});
const tasks=await create("Lead Finder · Search Tasks",{Name:title,Product:relation(products),Countries:rich,Languages:rich,Status:select(["queued","running","paused","completed","failed","cancelled"]),Progress:number,"Keyword Count":number,"Domains Found":number,"Companies Processed":number,"Valid Companies":number,"Max Keywords":number,"Max Results":number,"Min Score":number,Keywords:rich,"Error Message":rich,"Created At":date,"Started At":date,"Completed At":date});
const companies=await create("Lead Finder · Companies",{Name:title,"Local Name":rich,Domain:url,Website:url,Country:select([]),Region:rich,City:rich,Address:rich,"Postal Code":rich,Phone:phone,"General Email":email,"Company Type":select([]),Applications:multi,"Relevant Products":multi,Description:rich,"Lead Score":number,"Lead Grade":select(["A","B","C","D"]),"Score Details":rich,"Evidence Summary":rich,"Evidence URL":url,"Development Status":select(["未联系","准备联系","已发送邮件","已回复","有兴趣","无兴趣","需要跟进","已成交","无效客户"]),Priority:checkbox,"Source Task":relation(tasks),"First Found At":date,"Last Verified At":date,"Updated At":date});
const contacts=await create("Lead Finder · Contacts",{Name:title,Company:relation(companies),"Job Title":rich,Department:rich,Email:email,Phone:phone,"Profile URL":url,"Source URL":url,"Email Status":select(["published","directory","predicted","unknown"]),Confidence:select(["high","medium","low"]),"Last Verified At":date});
const sources=await create("Lead Finder · Sources",{Title:title,Company:relation(companies),Task:relation(tasks),"Page URL":url,"Page Type":select(["search_result","homepage","product","application","contact","team","other"]),"Search Keyword":rich,"Search Rank":number,"Evidence Text":rich,"Fetched At":date});
console.log("将以下 ID 写入 .env（不要提交 .env）：");console.log(`NOTION_PRODUCTS_DATABASE_ID=${products}\nNOTION_SEARCH_TASKS_DATABASE_ID=${tasks}\nNOTION_COMPANIES_DATABASE_ID=${companies}\nNOTION_CONTACTS_DATABASE_ID=${contacts}\nNOTION_SOURCES_DATABASE_ID=${sources}`);

